# Generated by Django 4.0 on 2023-06-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Sub_category',
        ),
    ]
